language: python
python:
- '3.6'
- '3.7'
- '3.8'
services:
- mongodb
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run -m unittest discover --verbose --start-directory tests/ --pattern "test_*.py" --top-level-directory tests/
after_success:
- coveralls
deploy:
  provider: pypi
  user: techlee
  password:
    secure: pTL4bF82LZ+Usn7rhm/7tPDz4QiF+RWuVyu+7aNtgqy4JZ5nCloIxohSxODCr58vYabAMecxwCsvCVm7DSWeJiYzFiyWMiEIRxmuc6LHSNnG8pYIHuj9qBcOdyshQbN5ALpuvnpFX2sUQ20hy3ge6cdFT4xLZAm4nzmNnR6e20MNOT675agdNfgDsjnNEBV7lCGfvpYtAJgaB95f8P24Q/WX6JevcrhCLLoLOnZdjt8RxvhV95QF03E3dI9c7d1NwFEZ/IbK2WfXjZ8rY2vYutscSlvag2r+N/ZVlOwTQvwWeZHXkDu6bRsV2mKC1Sq2J6q6mwtFm81YLB5A0RgMIJu+4Ec36Xl1HxRCBgDxDh4WfZkx/yZJsAMqTKVnFsImDt76MD6sDyemG/cPhli3qkAYazgdL2rv9l8KQWVwIhUTN4zOigzDpoEGIvk3DjrAoCoyP/9U5oagBnHSdL/e5jHFoJQ9CS8RRUYvsez6QWE7V06qRLfTSpxmxzvFrA0RENw6RcpabVmbFac/HdMyv9aFL8Z/bWHf2vkyAYUDBDiyFKKYcGWxTsS3L+fTDvyycfy8NJ3jSgloJiXH2FFsEJ03ZxgCIONNMw8gZ58gglJC0jJHZbzjIAl7oNcm+6S0T56y3H6Hb2zQk0eRD6qiY6RQZowc+HH9Is0ejNhW9zc=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    python: '3.6'